#!/bin/sh

is_closed() {
	local _module_addr="${1}"
	local _ret
	_ret="$(i2c get "${_module_addr}")"
	if test "${_ret}" = 0; then
		printf 'true\n'
	else
		printf 'false\n'
	fi
}

main() {
	local _first=48
	local _last=53
	for i in $(seq "${_first}" "${_last}" | tac); do
		if ! _cur_is_closed="$(is_closed "${i}")"; then
			printf 'module %s is unavailable\n' "${i}" >&2
			exit 1
		fi

		if ! "${_cur_is_closed}"; then
			continue
		fi

		printf 'opening module %s\n' "${i}"
		i2c set "${i}" 1
		sleep 3
		_cur_is_closed="$(is_closed "${i}")"
		if "${_cur_is_closed}"; then
			printf 'module %s got stuck\n' "${i}" >&2
			exit 1
		fi
		exit 0
	done

	printf 'All modules are already open\n' >&2
	exit 1
}

set -e
set -u

main
