#!/bin/sh

set -e
set -u

script_path="$(cd "$(dirname "${0}")" && pwd)"
export PATH="${PATH}:${script_path}"

cur="$(i2c get 8)"

case "${cur}" in
	0)
		printf 'open\n' >&2
		i2c set 8 1
		;;
	1)
		printf 'close\n' >&2
		i2c set 8 0
		;;
	*)
		printf 'error\n' >&2
		exit 1
		;;
esac
